# Generated by Django 4.1.3 on 2023-09-09 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('subject', models.CharField(choices=[('English', 'English'), ('Mathematics', 'Mathematics'), ('Science', 'Science')], max_length=50)),
                ('description', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('contact_no', models.CharField(max_length=15)),
                ('sms_no', models.CharField(max_length=15)),
                ('recurrence', models.CharField(choices=[('7Days', '7 Days'), ('5Days', '5 Days'), ('3Days', '3 Days'), ('2Days', '2 Days')], max_length=10)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
